apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quarkus-imperative-runner
    app.kubernetes.io/version: latest
  name: quarkus-imperative-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-imperative-runner
      app.kubernetes.io/version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quarkus-imperative-runner
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: quarkus-imperative-runner
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JDBC_DATASOURCE_URL
              value: "jdbc:postgresql://127.0.0.1:30828/books_database"
          image: localhost:32000/quarkus-imperative-runner
          imagePullPolicy: IfNotPresent
          name: quarkus-imperative-runner
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quarkus-imperative-runner
    app.kubernetes.io/version: latest
  name: quarkus-imperative-runner
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 31827
      port: 8080
      targetPort: 8086
  selector:
    app.kubernetes.io/name: quarkus-imperative-runner
    app.kubernetes.io/version: latest
