server:
  port : 8085

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/books_database
    username: book
    password: book

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: SpringBootImperativeBooksApi