server:
  port : 8085

spring:
  output:
    ansi:
      enabled: always
logging:
  level:
    web: INFO
    org.springframework.jdbc.core: TRACE
  datasource:
    url: jdbc:postgresql://localhost:5432/books_database
    driverClassName: org.postgresql.Driver
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #driverClassName: org.h2.Driver
    sql-script-encoding: UTF-8
    initialization-mode: embedded
    username: book
    password: book

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: SpringBootImperativeBooksApi