version: '3.7'
services:
  nodejsapi:
    image: 'docker.io/node/node-books-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: nodejsapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.2.197:5432/books_database?createDatabaseIfNotExist=true
    expose:
      - 8085
    ports:
      - 3001:3001
    restart: unless-stopped

  springbootreimperativejdbcapi:
    image: 'docker.io/library/sb-imperative-jdbc-api:1.0-SNAPSHOT'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: springbootreimperativejdbcapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.2.197:5432/books_database?createDatabaseIfNotExist=true
    expose:
      - 8085
    ports:
      - 8085:8085
    restart: unless-stopped

  springbootreimperativejpaapi:
    image: 'docker.io/library/sb-imperative-jpa-api:1.0-SNAPSHOT'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: springbootreimperativejpaapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.2.197:5432/books_database?createDatabaseIfNotExist=true
    expose:
      - 8086
    ports:
      - 8086:8086
    restart: unless-stopped

  springbootreactiveapi:
    image: 'docker.io/library/sb-reactive-api:1.0-SNAPSHOT'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: springbootsbreactiveapi
    environment:
      - DATABASE_HOST=192.168.2.197
    expose:
      - 8084
    ports:
      - 8084:8084
    restart: unless-stopped

  quarkusreactiveapi:
    image: 'docker.io/quarkus/quarkus-reactive-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusreactiveapi
    environment:
      - POSTGRESQL_REACTIVE_URL=postgresql://192.168.2.197:5432/books_database
    expose:
      - 8087
    ports:
      - 8087:8087
    restart: unless-stopped

  quarkusimperativejdbcapi:
    image: 'docker.io/quarkus/quarkus-imperative-jdbc-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusimperativejdbcapi
    environment:
      - POSTGRESQL_IMPERATIVE_URL=jdbc:postgresql://192.168.2.197:5432/books_database
      - POSTGRESQL_IMPERATIVE_PW=book
    expose:
      - 8088
    ports:
      - 8088:8088
    restart: unless-stopped

  quarkusimperativejpaapi:
    image: 'docker.io/quarkus/quarkus-imperative-jpa-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusimperativejpaapi
    environment:
      - POSTGRESQL_IMPERATIVE_URL=jdbc:postgresql://192.168.2.197:5432/books_database
    expose:
      - 8089
    ports:
      - 8089:8089
    restart: unless-stopped