version: '3.7'
services:
  postgres-quarkusreactiveapi:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    network_mode: bridge
    container_name: postgres-quarkusreactiveapi
    volumes:
      - ../../infrastructure/db-init/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5487
    ports:
      - 5487:5432
    environment:
      - POSTGRES_PASSWORD=book
      - POSTGRES_USER=book
      - POSTGRES_DB=books_database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  quarkusreactiveapi:
    image: 'docker.io/quarkus/quarkus-reactive-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusreactiveapi
    environment:
      - POSTGRESQL_REACTIVE_URL=postgresql://192.168.2.49:5487/books_database
    expose:
      - 8087
    ports:
      - 8087:8087
    restart: unless-stopped
    depends_on:
      - postgres-quarkusreactiveapi

  quarkusreactiveapi-jvm:
    image: 'docker.io/quarkus/quarkus-reactive-api-jvm'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusreactiveapi-jvm
    environment:
      - POSTGRESQL_REACTIVE_URL=postgresql://192.168.2.49:5487/books_database
    expose:
      - 8087
    ports:
      - 8097:8087
    restart: unless-stopped
    depends_on:
      - postgres-quarkusreactiveapi


volumes:
  postgres_data:
