version: '3.7'
services:
  postgres-quarkusimperativejdbcapi:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    network_mode: bridge
    container_name: postgres-quarkusimperativejdbcapi
    volumes:
      - ../../infrastructure/db-init/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5488
    ports:
      - 5488:5432
    environment:
      - POSTGRES_PASSWORD=book
      - POSTGRES_USER=book
      - POSTGRES_DB=books_database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  quarkusimperativejdbcapi:
    image: 'docker.io/quarkus/quarkus-imperative-jdbc-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusimperativejdbcapi
    environment:
      - POSTGRESQL_IMPERATIVE_URL=jdbc:postgresql://192.168.2.197:5488/books_database?createDatabaseIfNotExist=true
    expose:
      - 8088
    ports:
      - 8088:8088
    restart: unless-stopped
    depends_on:
      - postgres-quarkusimperativejdbcapi

volumes:
  postgres_data:
