global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'springBootReactiveBookApi'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.49:8084']

  - job_name: 'springBootImperativeBookApi'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.49:8085']

  - job_name: 'quarkusReactiveBookApi'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.49:8086']

  - job_name: 'quarkusImperativeBookApi'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.49:8087']

  - job_name: 'cAdvisor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.2.49:8080' ]
        labels:
          group: 'cadvisor'
