version: '3.7'
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: my-postgres
    volumes:
      - ./db-init/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=book
      - POSTGRES_USER=book
      - POSTGRES_DB=books_database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  monitoring-prometheus:
    image: "prom/prometheus:v2.26.0"
    container_name: "books-monitoring-prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  monitoring-grafana:
    image: "grafana/grafana:7.5.4"
    container_name: "books-monitoring-grafana"
    ports:
      - 3000:3000

volumes:
  postgres_data:


