version: '3.7'
services:
  postgres-quarkusimperativejpaapi:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    network_mode: bridge
    container_name: postgres-quarkusimperativejpaapi
    volumes:
      - ../../infrastructure/db-init/setup.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5489
    ports:
      - 5489:5432
    environment:
      - POSTGRES_PASSWORD=book
      - POSTGRES_USER=book
      - POSTGRES_DB=books_database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  quarkusimperativejpaapi:
    image: 'docker.io/quarkus/quarkus-imperative-jpa-api'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusimperativejpaapi
    environment:
      - POSTGRESQL_IMPERATIVE_URL=jdbc:postgresql://192.168.2.49:5489/books_database?createDatabaseIfNotExist=true
    expose:
      - 8089
    ports:
      - 8089:8089
    restart: unless-stopped
    depends_on:
      - postgres-quarkusimperativejpaapi

  quarkusimperativejpaapi-jvm:
    image: 'docker.io/quarkus/quarkus-imperative-jpa-api-jvm'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2048MB
        reservations:
          cpus: 0.5
          memory: 256MB
    network_mode: bridge
    container_name: quarkusimperativejpaapi-jvm
    environment:
      - POSTGRESQL_IMPERATIVE_URL=jdbc:postgresql://192.168.2.49:5489/books_database?createDatabaseIfNotExist=true
    expose:
      - 8089
    ports:
      - 8099:8089
    restart: unless-stopped
    depends_on:
      - postgres-quarkusimperativejpaapi

volumes:
  postgres_data:
